import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import DeveloperButton from "@/components/developerButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        

        <title>大学入試国語 出典本ランキング｜過去問で出た本を年度・科目別に検索</title>
        <meta name="description" content="大学入試国語に出題された出典本をランキング形式で紹介。年度（2015〜2025）・国立/私立・現代文/古文/漢文で絞り込め、Amazonリンク付きで購入も可能。受験対策・読書リスト・学び直しに最適です。" />
        <meta name="keywords" content="大学入試, 国語, 出典, 本, ランキング, 過去問, 受験, 読書, 教養" />
        <meta name="author" content="Ryotaro" />
        <link rel="canonical" href="https://%%BASE_URL%%/" />

        <meta name="robots" content="index,follow" />

        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="大学入試国語 出典本ランキング" />
        <meta property="og:title" content="大学入試国語 出典本ランキング｜過去問で出た本を年度・科目別に検索" />
        <meta property="og:description" content="大学入試国語に出題された出典本をランキング形式で紹介。年度・国立/私立・現代文/古文/漢文で絞り込み可能。Amazonリンク付き。" />
        <meta property="og:url" content="https://%%BASE_URL%%/" />
        <meta property="og:image" content="https://%%BASE_URL%%/%%OG_IMAGE%%" />
        <meta property="og:image:alt" content="大学入試国語 出典本ランキング — サイトのサムネイル" />


        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="%%TWITTER_HANDLE%%" />
        <meta name="twitter:title" content="大学入試国語 出典本ランキング" />
        <meta name="twitter:description" content="年度・大学別・科目別で絞り込める、大学入試の出典本ランキング。Amazonリンク付きで購入も可能。" />
        <meta name="twitter:image" content="https://%%BASE_URL%%/%%OG_IMAGE%%" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br from-slate-100 via-blue-50 to-teal-50 relative">
          <DeveloperButton />
          {/* Header */}
          <Header />

          {/* Main content wrapped in a container */}
          <div className="container mx-auto px-4 py-8 max-w-6xl">
            {children}
          </div>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
